### ISSUE TITLE
vacenc

### ISSUE THREAD

**Issue by tho1294** [hannob/vacdec#11]
hello do you have an idea to do the reverse : generate qrcode base45 from json?

thank's

**Comment by Salamafet** [comment]
Have you found a solution?

**Comment by tho1294** [comment]
yes i'm lock on the certificate for now

**Comment by santinoq** [comment]
salve volevo sapere qualcosa in piu su certificato green pass:HC1:6BFOXN%TS3DHPVO13J
praticamente o inserito il mio green pass allinterno di un programma per de codificarlo :
il programma si chiama encoding &decoding online tools, e o usato
base45/zlib/cose/cbor.
vorrei sapere come posso tornare in dietro al formato della stringa iniziali....
chi mi potrebbe gentilmente spigare ,o con un altro programma.
grazie mille
