### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by qq5678** [hannob/vacdec#14]
Hey

i was wondering if there is any reverse process .

i have the json built in and I would like to convert it to QR

would be awesome if you could provide me any tutorial or other github links . Couldnt find any

**Comment by thejacko12354** [comment]
That's Not possible with this Library. 

The only way to get a valid QR-Code is, that you get yourself vaccinated.

**Comment by Dakkaron** [comment]
How do you guys imagine that this script could generate a signed QR code without the key to sign it?

To put it simply: No key, no signing. The QR code is not encrypted (which would make it impossible to be read without the fitting key), but it is signed (which means, you can verify that it was signed with the correct key).

Reading signed messages is trivial (as it is supposed to be).

Creating signed messages requires a key.

If you want a signed QR code, go get vaccinated!
