### ISSUE TITLE
Can you please make a video tutorial ?

### ISSUE THREAD

**Issue by dstouthamer** [hannob/vacdec#18]
So sir can you please make a video tutorial for me, because i don't understand it perfectly.
I live in the Netherlands so it would be very nice if you can show how to make that vaccination qr code.

**Comment by rejas** [comment]
To quote from another Issue:

That's Not possible with this Library.

The only way to get a valid QR-Code is, that you get yourself vaccinated.

**Comment by KanekiLeChomeur** [comment]
> So sir can you please make a video tutorial for me, because i don't understand it perfectly. I live in the Netherlands so it would be very nice if you can show how to make that vaccination qr code.

Hello, if you want to learn how to use Termux, there are some tutorials on Termux and Linux Terminals(Termux is emulating Linux Terminal), so there is no need to create an Issue for that.
