### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by idefixgallier** [hannob/vacdec#21]
Hey!

I have a question to this beautiful peace of software ...
I don't know if its an issue with Jaris Fork or in the main branch but as i am lacking
python knowledge i humble ask anyways:

# /vacdec/vacdec --image-file /tmp/gettinger_v3.png
Traceback (most recent call last):
  File "/vacdec/vacdec", line 241, in <module>
    main()
  File "/vacdec/vacdec", line 228, in main
    covid_cert_data = data[0].data.decode()
**IndexError: list index out of range**

Can anyone give me a hint why this certificate shows that error please?

Kind regards
Martin

**Comment by hannob** [comment]
This likely just means your QR code is either not an EU certificate (some countries issue their own certificates in a different format) or the picture quality is not good enough to properly read the QR code.

I can check if you send me the certificate via mail.

**Comment by idefixgallier** [comment]
Thanky you sir - This would be really really helpful!

I have two versions - the QR Code alone and the original official certificate.
 Austrian Greencheck app validates both correctly.
May i kindly ask you for an email address as these are not my personal certificates and
i do not want to attach them on this platform ...

**Comment by idefixgallier** [comment]
Never mind ... found one on your website ;)

**Comment by hannob** [comment]
My contact info: https://hboeck.de/en/contact.html

**Comment by hannob** [comment]
Clarified via email, was just an image quality issue, pyzbar was unable to decode.
